# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2.1'

networks:
  sub2-network:
    name: sub2-network
    ipam:
      driver: default
      config: 
        - subnet: 123.133.123.0/16
services:
  orderer2.orgorderer.com:
    container_name: orderer2.orgorderer.com
    image: hyperledger/fabric-orderer:1.4.7
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=ordererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer/msp
      - ORDERER_GENERAL_LISTENPORT=36060
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/orderer/msp/cacerts/ca-orgorderer-com-8054.pem]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/orderer/msp/cacerts/ca-orgorderer-com-8054.pem]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    logging:
      driver: none    
    volumes:
      - ../scripts/container:/scripts
      - ../../logs/container_logs/orderer2.orgorderer.com:/log
      - ../channel-artifacts/genesis.block:/etc/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/orgorderer.com/users/Admin@orgorderer.com/msp/:/etc/hyperledger/orderer/admin/msp
      - ../crypto-config/ordererOrganizations/orgorderer.com/orderers/orderer2.orgorderer.com:/etc/hyperledger/orderer
      - ../../data/production/orderer2.orgorderer.com/:/var/hyperledger/production
    command: /bin/bash -c '/scripts/start-orderer2.sh'
    ports:
      - 36060:36060
    extra_hosts:
      - orderer0.orgorderer.com:192.168.181.100
      - orderer1.orgorderer.com:192.168.181.100
      - peer0.orgmain.com:192.168.181.100
      - peer0.orgsub1.com:192.168.181.100
    networks:
      - sub2-network

  peer1.orgsub2.com:
    container_name: peer1.orgsub2.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.orgsub2.com
      - CORE_PEER_ADDRESS=peer1.orgsub2.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.orgsub2.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.orgsub2.com:9051
      - CORE_PEER_LOCALMSPID=sub2MSP
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/msp/cacerts/ca-orgsub2-com-9070.pem
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.orgsub2.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=sub2_dev0
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=sub2!
      - CORE_LEDGER_STATE_COUCHDBCONFIG_REQUESTTIMEOUT=90s
      - CORE_CHAINCODE_EXECUTETIMEOUT=90s
      - CORE_PEER_KEEPALIVE_CLIENT_TIMOUT=90s
      - CORE_PEER_KEEPALIVE_DELIVERYCLIENT_TIMEOUT=90s
    command: /bin/bash -c '/scripts/start-peer.sh'  
    logging:
      driver: none     
    volumes:
        - /var/run/:/host/var/run/
        - ../scripts/container:/scripts
        - ../../logs/container_logs/peer1.orgsub2.com:/log
        - ../crypto-config/peerOrganizations/orgsub2.com/peers/peer1.orgsub2.com/:/opt/gopath/src/github.com/hyperledger/fabric/peer
        - ../../data/production/peer1.orgsub2.com:/var/hyperledger/production
    depends_on:
      - couchdb1.orgsub2.com
    ports:
      - 9051:9051
    extra_hosts:
      - orderer0.orgorderer.com:192.168.181.100
      - orderer1.orgorderer.com:192.168.181.100
      - peer0.orgmain.com:192.168.181.100
      - peer0.orgsub1.com:192.168.181.100
    networks:
      - sub2-network

  couchdb1.orgsub2.com:
    container_name: couchdb1.orgsub2.com
    image: hyperledger/fabric-couchdb:0.4.20
    environment:
      - COUCHDB_USER=sub2_dev0
      - COUCHDB_PASSWORD=sub2!
    volumes:
        - ../../data/couchdb/couchdb1.orgsub2.com:/opt/couchdb/data
        - ../../logs/container_logs/couchdb1.orgsub2.com:/opt/couchdb/log/
        - ../config/couchdb/local1.ini:/opt/couchdb/etc/local.ini
    ports:
      - "5984:5984"
    logging:
      driver: none
    networks:
      - sub2-network
  setup:
    container_name: setup
    extends:
      file: peer-base.yaml
      service: ca-env
    image: hyperledger/fabric-ca:1.4.7
    environment:
      - ORDERER_HOME=/etc/hyperledger/orderer
      - PEER_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c '/scripts/setup-fabric.sh; sleep 99999'
    volumes:
      - ../scripts/container:/scripts
      - ../crypto-config:/crypto-config
      - ../channel-artifacts:/root/data
    networks:
      - sub2-network


  ca.orgsub2.com:
    container_name: ca.orgsub2.com
    image: hyperledger/fabric-ca:1.4.7
    extends:
      file: peer-base.yaml
      service: ca-env
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_CSR_CN=ca.orgsub2.com
      - FABRIC_CA_SERVER_CSR_HOSTS=ca.orgsub2.com
      - FABRIC_CA_SERVER_DEBUG=true
      - FABRIC_CA_SERVER_CA_NAME=ca-main
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_PORT=9070
      - FABRIC_CA_SERVER_SIGNING_DEFAULT_EXPIRY=876600h
      - FABRIC_CA_SERVER_SIGNING_PROFILES_TLS_EXPIRY=876600h
      - FABRIC_CA_SERVER_CSR_CA_EXPIRY=876600h
    ports:
      - 9071:9071
    command: /bin/bash -c '/scripts/start-root-ca.sh'
    logging:
      driver: none 
    volumes:
      - ../scripts/container:/scripts
      - ../crypto-config:/crypto-config
      - ../../data/ca/ca.orgsub2.com:/etc/hyperledger/fabric-ca
      - ../../logs/container_logs/ca.orgsub2.com:/log
    networks:
      - sub2-network
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4.7
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer1.orgsub2.com:9051
      - CORE_PEER_LOCALMSPID=sub2MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgsub2.com/peers/peer1.orgsub2.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgsub2.com/peers/peer1.orgsub2.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgsub2.com/peers/peer1.orgsub2.com/msp/cacerts/ca-orgsub2-com-9070.pem
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgsub2.com/users/Admin@orgsub2.com/msp/
      - TZ=Asia/Seoul
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash 
    volumes:
        - /var/run/:/host/var/run/
        - ../scripts/cron:/scripts
        - ../../logs/container_logs:/logs
        - ../chaincode/:/opt/gopath/src/github.com/chaincode
        - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
    extra_hosts:
      - orderer0.orgorderer.com:192.168.181.100
      - orderer1.orgorderer.com:192.168.181.100
      - peer0.orgmain.com:192.168.181.100
      - peer0.orgsub1.com:192.168.181.100
    networks:
      - sub2-network


  
